"""Measurement database model

Revision ID: dbf90bd1a0b8
Revises: 9cee9d84f065
Create Date: 2022-02-07 22:58:28.097873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf90bd1a0b8'
down_revision = '9cee9d84f065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('heart_rate_value', sa.Float(), nullable=True),
    sa.Column('blood_pressure_systolic_value', sa.Float(), nullable=True),
    sa.Column('blood_pressure_diastolic_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_data.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    # ### end Alembic commands ###
