# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hmsensyne ios mvp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hmsensyne ios mvp
  pod 'Alamofire', '~> 5.5'
  pod 'OpenCV'
  pod 'Charts'
  pod 'ExytePopupView'

  target 'hmsensyne ios mvpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hmsensyne ios mvpUITests' do
    # Pods for testing
  end

end
